// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main
void ui_main_screen_init(void);
lv_obj_t * ui_main;
lv_obj_t * ui_PageSelector;
lv_obj_t * ui_DevicesPage;
lv_obj_t * ui_ControlPage;
lv_obj_t * ui_SettingsPage;
lv_obj_t * ui_JContentPanel;
lv_obj_t * ui_JHeaderPanel;
lv_obj_t * ui_JoystickSettingsLabel;
void ui_event_InvertJoystickCheckbox(lv_event_t * e);
lv_obj_t * ui_InvertJoystickCheckbox;
lv_obj_t * ui_JoystickSensitivityContainer;
lv_obj_t * ui_JoystickSensitivityLabelContainer;
lv_obj_t * ui_JoystickSensitivityLabel;
void ui_event_JoystickSensitivitySliderResetButton(lv_event_t * e);
lv_obj_t * ui_JoystickSensitivitySliderResetButton;
lv_obj_t * ui_JoystickSensitivitySliderResetLabel;
void ui_event_JoystickSensitivitySlider(lv_event_t * e);
lv_obj_t * ui_JoystickSensitivitySlider;
void ui_event_JoystickCalibrateButton(lv_event_t * e);
lv_obj_t * ui_JoystickCalibrateButton;
lv_obj_t * ui_JoystickCalibrateLabel;
lv_obj_t * ui_AboutPage;
lv_obj_t * ui_qrContainer;
lv_obj_t * ui_qrCode;
lv_obj_t * ui_qrLabel;
lv_obj_t * ui_Container7;
lv_obj_t * ui_DeviceInfoLabel;
lv_obj_t * ui_DeviceInformation;
lv_obj_t * ui_battInfo;
// CUSTOM VARIABLES
lv_obj_t * uic_main;
lv_obj_t * uic_PageSelector;
lv_obj_t * uic_DSContentPanel;
lv_obj_t * uic_JoystickSettingsLabel;
lv_obj_t * uic_qrContainer;
lv_obj_t * uic_qrPlaceholder;
lv_obj_t * uic_qrLabel;
lv_obj_t * uic_DeviceInfoLabel;
lv_obj_t * uic_DeviceInformation;
lv_obj_t * uic_battInfo;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_InvertJoystickCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnInvertJoystickCheckboxChecked(e);
    }
}

void ui_event_JoystickSensitivitySliderResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        JoystickSensitivitySliderResetButtonClicked(e);
    }
}

void ui_event_JoystickSensitivitySlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnJoystickSensitivitySliderChange(e);
    }
}

void ui_event_JoystickCalibrateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        OnCalibrateButtonClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
