// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_PageSelector;
extern lv_obj_t * ui_DevicesPage;
extern lv_obj_t * ui_ControlPage;
extern lv_obj_t * ui_SettingsPage;
extern lv_obj_t * ui_JContentPanel;
extern lv_obj_t * ui_JHeaderPanel;
extern lv_obj_t * ui_JoystickSettingsLabel;
void ui_event_InvertJoystickCheckbox(lv_event_t * e);
extern lv_obj_t * ui_InvertJoystickCheckbox;
extern lv_obj_t * ui_JoystickSensitivityContainer;
extern lv_obj_t * ui_JoystickSensitivityLabelContainer;
extern lv_obj_t * ui_JoystickSensitivityLabel;
void ui_event_JoystickSensitivitySliderResetButton(lv_event_t * e);
extern lv_obj_t * ui_JoystickSensitivitySliderResetButton;
extern lv_obj_t * ui_JoystickSensitivitySliderResetLabel;
void ui_event_JoystickSensitivitySlider(lv_event_t * e);
extern lv_obj_t * ui_JoystickSensitivitySlider;
void ui_event_JoystickCalibrateButton(lv_event_t * e);
extern lv_obj_t * ui_JoystickCalibrateButton;
extern lv_obj_t * ui_JoystickCalibrateLabel;
extern lv_obj_t * ui_AboutPage;
extern lv_obj_t * ui_qrContainer;
extern lv_obj_t * ui_qrCode;
extern lv_obj_t * ui_qrLabel;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_DeviceInfoLabel;
extern lv_obj_t * ui_DeviceInformation;
extern lv_obj_t * ui_battInfo;
// CUSTOM VARIABLES
extern lv_obj_t * uic_main;
extern lv_obj_t * uic_PageSelector;
extern lv_obj_t * uic_DSContentPanel;
extern lv_obj_t * uic_JoystickSettingsLabel;
extern lv_obj_t * uic_qrContainer;
extern lv_obj_t * uic_qrPlaceholder;
extern lv_obj_t * uic_qrLabel;
extern lv_obj_t * uic_DeviceInfoLabel;
extern lv_obj_t * uic_DeviceInformation;
extern lv_obj_t * uic_battInfo;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pointer_png);    // assets/pointer.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
