// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PageSelector = lv_tabview_create(ui_main, LV_DIR_LEFT, 100);
    lv_obj_set_width(ui_PageSelector, lv_pct(100));
    lv_obj_set_height(ui_PageSelector, lv_pct(100));
    lv_obj_set_x(ui_PageSelector, -1);
    lv_obj_set_y(ui_PageSelector, 0);
    lv_obj_clear_flag(ui_PageSelector, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PageSelector, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PageSelector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_DevicesPage = lv_tabview_add_tab(ui_PageSelector, "Devices");
    lv_obj_set_style_bg_color(ui_DevicesPage, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DevicesPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlPage = lv_tabview_add_tab(ui_PageSelector, "Control");
    lv_obj_set_style_bg_color(ui_ControlPage, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ControlPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPage = lv_tabview_add_tab(ui_PageSelector, "Settings");
    lv_obj_set_flex_flow(ui_SettingsPage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_SettingsPage, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JContentPanel = lv_obj_create(ui_SettingsPage);
    lv_obj_set_width(ui_JContentPanel, lv_pct(100));
    lv_obj_set_height(ui_JContentPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_JContentPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_JContentPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_JContentPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_JContentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_JContentPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_JContentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_JContentPanel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JHeaderPanel = lv_obj_create(ui_JContentPanel);
    lv_obj_set_width(ui_JHeaderPanel, lv_pct(100));
    lv_obj_set_height(ui_JHeaderPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JHeaderPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_JHeaderPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_JHeaderPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_JHeaderPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JoystickSettingsLabel = lv_label_create(ui_JHeaderPanel);
    lv_obj_set_width(ui_JoystickSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JoystickSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JoystickSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JoystickSettingsLabel, "Joystick");

    ui_InvertJoystickCheckbox = lv_checkbox_create(ui_JContentPanel);
    lv_checkbox_set_text(ui_InvertJoystickCheckbox, "Invert Joystick");
    lv_obj_set_width(ui_InvertJoystickCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InvertJoystickCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InvertJoystickCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InvertJoystickCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_JoystickSensitivityContainer = lv_obj_create(ui_JContentPanel);
    lv_obj_remove_style_all(ui_JoystickSensitivityContainer);
    lv_obj_set_height(ui_JoystickSensitivityContainer, 70);
    lv_obj_set_width(ui_JoystickSensitivityContainer, lv_pct(100));
    lv_obj_set_x(ui_JoystickSensitivityContainer, -1);
    lv_obj_set_y(ui_JoystickSensitivityContainer, 0);
    lv_obj_set_align(ui_JoystickSensitivityContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_JoystickSensitivityContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_JoystickSensitivityContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_JoystickSensitivityContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_JoystickSensitivityContainer, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JoystickSensitivityContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JoystickSensitivityLabelContainer = lv_obj_create(ui_JoystickSensitivityContainer);
    lv_obj_remove_style_all(ui_JoystickSensitivityLabelContainer);
    lv_obj_set_height(ui_JoystickSensitivityLabelContainer, 50);
    lv_obj_set_width(ui_JoystickSensitivityLabelContainer, lv_pct(100));
    lv_obj_set_align(ui_JoystickSensitivityLabelContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_JoystickSensitivityLabelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JoystickSensitivityLabel = lv_label_create(ui_JoystickSensitivityLabelContainer);
    lv_obj_set_width(ui_JoystickSensitivityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JoystickSensitivityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JoystickSensitivityLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_JoystickSensitivityLabel, "Joystick Sensitivity");

    ui_JoystickSensitivitySliderResetButton = lv_btn_create(ui_JoystickSensitivityLabelContainer);
    lv_obj_set_height(ui_JoystickSensitivitySliderResetButton, 30);
    lv_obj_set_width(ui_JoystickSensitivitySliderResetButton, lv_pct(15));
    lv_obj_set_align(ui_JoystickSensitivitySliderResetButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_JoystickSensitivitySliderResetButton,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_JoystickSensitivitySliderResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_JoystickSensitivitySliderResetButton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_JoystickSensitivitySliderResetButton, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_JoystickSensitivitySliderResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JoystickSensitivitySliderResetLabel = lv_label_create(ui_JoystickSensitivitySliderResetButton);
    lv_obj_set_width(ui_JoystickSensitivitySliderResetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JoystickSensitivitySliderResetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JoystickSensitivitySliderResetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JoystickSensitivitySliderResetLabel, "Reset");

    ui_JoystickSensitivitySlider = lv_slider_create(ui_JoystickSensitivityContainer);
    lv_slider_set_range(ui_JoystickSensitivitySlider, 200, 600);
    lv_slider_set_value(ui_JoystickSensitivitySlider, 400, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_JoystickSensitivitySlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_JoystickSensitivitySlider, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_JoystickSensitivitySlider, 15);
    lv_obj_set_width(ui_JoystickSensitivitySlider, lv_pct(100));
    lv_obj_set_align(ui_JoystickSensitivitySlider, LV_ALIGN_CENTER);


    ui_JoystickCalibrateButton = lv_btn_create(ui_JContentPanel);
    lv_obj_set_height(ui_JoystickCalibrateButton, 50);
    lv_obj_set_width(ui_JoystickCalibrateButton, lv_pct(100));
    lv_obj_set_x(ui_JoystickCalibrateButton, -4);
    lv_obj_set_y(ui_JoystickCalibrateButton, -51);
    lv_obj_set_align(ui_JoystickCalibrateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JoystickCalibrateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_JoystickCalibrateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JoystickCalibrateLabel = lv_label_create(ui_JoystickCalibrateButton);
    lv_obj_set_width(ui_JoystickCalibrateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JoystickCalibrateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JoystickCalibrateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JoystickCalibrateLabel, "Calibrate Joystick");
    lv_obj_clear_flag(ui_JoystickCalibrateLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_AboutPage = lv_tabview_add_tab(ui_PageSelector, "About");
    lv_obj_set_style_bg_color(ui_AboutPage, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrContainer = lv_obj_create(ui_AboutPage);
    lv_obj_remove_style_all(ui_qrContainer);
    lv_obj_set_width(ui_qrContainer, 200);
    lv_obj_set_height(ui_qrContainer, 220);
    lv_obj_set_align(ui_qrContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_qrContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qrCode = lv_img_create(ui_qrContainer);
    lv_img_set_src(ui_qrCode, &ui_img_pointer_png);
    lv_obj_set_width(ui_qrCode, 200);
    lv_obj_set_height(ui_qrCode, 200);
    lv_obj_set_align(ui_qrCode, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_qrCode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qrCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qrLabel = lv_label_create(ui_qrContainer);
    lv_obj_set_width(ui_qrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_qrLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_qrLabel, "Link Here");
    lv_obj_set_style_text_color(ui_qrLabel, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_qrLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_qrLabel, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_AboutPage);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_height(ui_Container7, lv_pct(100));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DeviceInfoLabel = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_DeviceInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_DeviceInfoLabel, "Device Information");

    ui_DeviceInformation = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_DeviceInformation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceInformation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceInformation, 10);
    lv_obj_set_y(ui_DeviceInformation, 22);
    lv_label_set_text(ui_DeviceInformation, "Board ID: \nCPU:\nCPU Freq:\nSDK Version:\nLVGL Version:\nMAC Address:");

    ui_battInfo = lv_label_create(ui_main);
    lv_obj_set_width(ui_battInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battInfo, -33);
    lv_obj_set_y(ui_battInfo, 72);
    lv_obj_set_align(ui_battInfo, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_InvertJoystickCheckbox, ui_event_InvertJoystickCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JoystickSensitivitySliderResetButton, ui_event_JoystickSensitivitySliderResetButton,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JoystickSensitivitySlider, ui_event_JoystickSensitivitySlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JoystickCalibrateButton, ui_event_JoystickCalibrateButton, LV_EVENT_ALL, NULL);
    uic_main = ui_main;
    uic_PageSelector = ui_PageSelector;
    uic_DSContentPanel = ui_JContentPanel;
    uic_JoystickSettingsLabel = ui_JoystickSettingsLabel;
    uic_qrContainer = ui_qrContainer;
    uic_qrPlaceholder = ui_qrCode;
    uic_qrLabel = ui_qrLabel;
    uic_DeviceInfoLabel = ui_DeviceInfoLabel;
    uic_DeviceInformation = ui_DeviceInformation;
    uic_battInfo = ui_battInfo;

}
